region:
validation_year:
definition_path: /home/maxnutz/Documents/pypsa-at-validation/validation_pyam_structure/energy_balance_evaluation/sister_packages/energy-scenarios-at-workflow/definitions
# mapping_path: 

# relative validation tolerance:
validation_tolerance: 0.3

# Add special tolerances for special accounting levels:
validation_tolerance_sector:
  "Primary Energy": 0.05


